# TODO:
# * factor out common code
# * Asan
# * FreeBSD
# * gcc-9
# * armhf (https://www.acmesystems.it/arm9_toolchain)

language: python
os: linux
script: tests/1/run.sh
python: "3.6"
env:
  - CC=gcc
jobs:
  include:
    - stage: baseline
      name: python3.6-gcc-x86_64
      compiler: gcc
    - name: python3.6-clang-x86_64
      compiler: clang
      env:
        - CC=clang
    - stage: targets
      name: i386
      env:
        - ARCH=i386-linux-gnueabi
      addons:
        apt:
          packages:
            - gcc-multilib
    - name: arm
      env:
        - ARCH=arm-linux-gnueabi
      addons:
        apt:
          packages:
            - qemu-user
            - gcc-arm-linux-gnueabi
            - binutils-arm-linux-gnueabi
            - libc6-armel-cross
            - libc6-dev-armel-cross
    - name: aarch64
      env:
        - ARCH=aarch64-linux-gnueabi
      addons:
        apt:
          packages:
            - qemu-user
            - gcc-aarch64-linux-gnu
            - binutils-aarch64-linux-gnu
            - libc6-arm64-cross
            - libc6-dev-arm64-cross
    - stage: pythons
      name: python3.4
      python: "3.4"
    - name: python3.5
      python: "3.5"
    - name: pypy3.5
      python: "pypy3.5"
