# TODO:
# * factor out common code
# * Asan
# * FreeBSD
# * gcc-9
# * armhf (https://www.acmesystems.it/arm9_toolchain)

language: python
os: linux
script: tests/1/run.sh
python: "3.6"
env:
  - CC=gcc
jobs:
  include:
    - stage: baseline
      name: python3.6-gcc-x86_64
      compiler: gcc
    - name: python3.6-clang-x86_64
      compiler: clang
      env:
        - CC=clang
    - stage: targets
      name: i386
      env:
        - ARCH=i386-linux-gnueabi
      addons:
        apt:
          packages:
            - gcc-multilib
    - stage: pythons
      name: python3.4
      python: "3.4"
    - name: python3.5
      python: "3.5"
    - name: pypy3.5
      python: "pypy3.5"
